# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
       - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      root_folder: "tests/"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Extract folders
        shell: pwsh
        run: |
          $subfolders = Get-ChildItem -Path "${{ env.root_folder }}" -Directory -Force -ErrorAction SilentlyContinue
              ForEach ($path in $subfolders) 
              {
                  # Set-Location $path.FullName
                  $fullpath = $path.FullName
                  $pathName = $path.BaseName
                  #Get all items 
                  $items = Get-ChildItem -Path $fullpath

                  $zipname = $path.name
                  $zippath = $zipname
                  Write-Host $zippath
                  Compress-Archive -Path $items -DestinationPath $zippath
              }
      - name: Add to release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "*.miz"
          allowUpdates: "true"
